dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
group: dev
language: python
python:
  - "3.7"
env:
  - SQLALCHEMY_DATABASE_URI=mysql://root:@127.0.0.1/mma_test
install: 
  - "pip install -r requirements.txt"
before_script:
  - sudo rm -f /etc/boto.cfg
  - mysql -h 127.0.0.1 -uroot -e 'create database mma_test;'
  - mysql -h 127.0.0.1 -uroot -e 'select @@version;'
script:
  - nosetests
