version: '3'
services:
  db:
    image: "mysql:5.6"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mma
      - MYSQL_DATABASE=mma
      - MYSQL_USER=mma
      - MYSQL_PASSWORD=mma
  
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SQLALCHEMY_DATABASE_URI=mysql://mma:mma@db/mma
      - BROKER_URL=redis://redis:6379/0
    command: python app.py runserver --host=0.0.0.0
  
  worker:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SQLALCHEMY_DATABASE_URI=mysql://mma:mma@db/mma
      - BROKER_URL=redis://redis:6379/0
    command: celery worker --app dexter.tasks --beat --concurrency 1 --loglevel info
  
  bash:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SQLALCHEMY_DATABASE_URI=mysql://mma:mma@db/mma
      - BROKER_URL=redis://redis:6379/0
    command: /bin/bash

volumes:
  archive-data: {}
  mysql-data: {}
  redis-data: {}
