version: '3'
services:
  db:
    image: "mysql:5.6.44"
    ports:
      - "33061:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dexter
      - MYSQL_ROOT_HOST=*
      - MYSQL_DATABASE=dexter
      - MYSQL_USER=dexter
      - MYSQL_PASSWORD=dexter
  
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  web:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SQLALCHEMY_DATABASE_URI=mysql://dexter:dexter@db/dexter
      - BROKER_URL=redis://redis:6379/0
    # command: python app.py runserver --host=0.0.0.0
    # command: gunicorn --workers 4 --worker-class gevent --timeout 600 --error-logfile - --access-logfile - --log-level debug -b 0.0.0.0:8000 app:app
  
  worker:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - SQLALCHEMY_DATABASE_URI=mysql://dexter:dexter@db/dexter
      - BROKER_URL=redis://redis:6379/0
    command: celery worker --app dexter.tasks --beat --concurrency 1 --loglevel info

volumes:
  archive-data: {}
  mysql-data: {}
  redis-data: {}
